# Tests are living outside the project :facepalm:
# They get the public API, then.
s/#include "(tt_metal\/)?(dev_msgs.h)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?(hlk_desc.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?(host_api\.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?(lock_free_queue.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?(program_cache.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?buffers\/(circular_buffer_types.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(assert.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(base.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(base.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(base_types.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(constants.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(core_coord.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(core_descriptor.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(env_lib.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(executor.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(logger.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(math.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(metal_soc_descriptor.h)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(test_common.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(test_tiles.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(tt_backend_api_types.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(utils.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?detail\/(util.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?hw\/inc\/(circular_buffer_constants.h)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?hw\/inc\/(dev_msgs.h)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/allocator\/(allocator.hpp)"/#include <tt-metalium\/\2>/
s/#include "(impl\/)?allocator\/(allocator.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/allocator\/(allocator_types.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/allocator\/(basic_allocator.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/allocator\/(l1_banking_allocator.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/allocator\/algorithms\/(allocator_algorithm.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/buffers\/(circular_buffer_types.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/buffers\/(semaphore.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/device\/(device.hpp)"/#include <tt-metalium\/device_impl.hpp>/
s/#include "(tt_metal\/)?impl\/dispatch\/(command_queue_interface.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/dispatch\/(cq_commands.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/dispatch\/(dispatch_core_common.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/dispatch\/(dispatch_core_manager.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/dispatch\/(lock_free_queue.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/dispatch\/(memcpy.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/dispatch\/(program_command_sequence.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/dispatch\/(work_executor.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/kernels\/(data_types.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/kernels\/(kernel_types.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/kernels\/(runtime_args_data.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/program\/(program.hpp)"/#include <tt-metalium\/program_impl.hpp>/
s/#include "(tt_metal\/)?impl\/program\/(program_device_map.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/sub_device\/(sub_device.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/sub_device\/(sub_device_manager.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/sub_device\/(sub_device_types.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?jit_build\/(build.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?jit_build\/(data_format.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?jit_build\/(settings.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?llrt\/(get_platform_architecture.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?llrt\/(hal.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?llrt\/(llrt.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?llrt\/(rtoptions.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?llrt\/(tt_cluster.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?llrt\/(tt_memory.h)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?tt_stl\/(aligned_allocator.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?tt_stl\/(concepts.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?tt_stl\/(reflection.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?tt_stl\/(span.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?tt_stl\/(type_name.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?tt_stl\/(unique_any.hpp)"/#include <tt-metalium\/\2>/
s/#include <(tt_metal\/)?common\/(assert.hpp)>/#include <tt-metalium\/\2>/

# End of host_api.hpp

s/#include "(tt_metal\/)?(blockfloat_common.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(bfloat16.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(bfloat4.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(bfloat8.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?detail\/(tt_metal.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?graph\/(graph_tracking.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/buffers\/(buffer.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/buffers\/(buffer_constants.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/buffers\/(global_circular_buffer.hpp)"/#include <tt-metalium\/global_circular_buffer_impl.hpp>/
s/#include "(tt_metal\/)?impl\/device\/(device_handle.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/tile\/(tile.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/dispatch\/(device_command.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)(types.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?tt_stl\/(slotmap.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/buffers\/(global_semaphore.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?distributed\/(mesh_device.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?distributed\/(mesh_device_view.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?include\/tt_metal\/(global_circular_buffer.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/dispatch\/(command_queue.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/dispatch\/(worker_config_buffer.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/trace\/(trace_buffer.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/device\/(device_pool.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?tools\/profiler\/(op_profiler.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?tools\/profiler\/(profiler.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?tools\/profiler\/(profiler_state.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?tools\/profiler\/(common.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/kernels\/(kernel.hpp)"/#include <tt-metalium\/\2>/
s/#include "(kernels\/)(kernel.hpp)"/#include <tt-metalium\/\2>/
s/#include "(kernels\/)(kernel_types.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/buffers\/(circular_buffer.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?common\/(work_split.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?impl\/trace\/(trace.hpp)"/#include <tt-metalium\/\2>/
s/#include "(tt_metal\/)?detail\/reports\/(compilation_reporter.hpp)"/#include <tt-metalium\/\2>/
s/#include "(test_tiles.hpp)"/#include <tt-metalium\/\1>/
s/#include "(bfloat16.hpp)"/#include <tt-metalium\/\1>/
s/#include "(tt_metal\/)?common\/(tilize_untilize.hpp)"/#include <tt-metalium\/\2>/
